version: '3.7'
services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ${POSTGRES_USER:-keycloak_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Str0ngP@ssw0rd!}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak_network
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start
    environment:
      KC_HTTP_PORT: 8181
      KC_HOSTNAME: https://keycloak.winfprojekt.de
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_PROXY_TRUSTED_ADDRESSES: "172.19.0.0/24,127.0.0.0/8"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-SuperSecretAdminP@ssw0rd}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/db
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak_db_user}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-Str0ngP@ssw0rd!}
    ports:
      - 8181:8181
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak_network
      - nginx-proxy-manager
volumes:
  postgres_data:
    name: keycloak-stack_postgres_data
    driver: local
networks:
  keycloak_network:
    driver: bridge
  nginx-proxy-manager:
    external: true