version: '3.8'

services:
  ayurly-frontend-app:
    image: ghcr.io/thi-projekte/ayurly-frontend:latest
    container_name: ayurly-frontend 
    restart: unless-stopped
    expose: # Macht den Port nur für andere Container im selben Docker-Netzwerk verfügbar
      - "80"
    networks:
      - nginx-proxy-manager 

networks:
  nginx-proxy-manager:
    external: true 