name: Data-Service CI - Build and Push Docker Image

on:
  push:
    branches:
      - main # Löst den Workflow nur bei Pushes auf den main-Branch aus
    paths:
      - 'ayurly-data-service/**' # Löst den Workflow nur aus, wenn Änderungen im Data-Service-Ordner erfolgen
      - '.github/workflows/data-service-ci.yml' # Löst auch aus, wenn der Workflow selbst geändert wird

jobs:
  build-and-push-data-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Benötigt, um in die GitHub Packages Container Registry zu pushen

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # Oder eine andere Distribution deiner Wahl

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/thi-projekte/ayurly-data-service
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image (Data Service)
        uses: docker/build-push-action@v6
        with:
          context: ./ayurly-data-service
          file: ./ayurly-data-service/src/main/docker/Dockerfile.jvm # Pfad zum Quarkus Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Quarkus build arguments (optional, falls benötigt)
          # build-args: |
          #  QUARKUS_PACKAGE_TYPE=uber-jar