name: Data-Service CI - Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'ayurly-data-service/**'
      - '.github/workflows/data-service-ci.yml'
  workflow_dispatch: # Ermöglicht manuelles Auslösen

jobs:
  build-and-push-data-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Aktiviert das Caching für Maven-Abhängigkeiten direkt hier
        
      - name: Make mvnw executable
        # Dieser Schritt ist notwendig, falls mvnw nicht mit Ausführungsrechten eingecheckt wurde
        working-directory: ./ayurly-data-service
        run: chmod +x mvnw

      - name: Build Data Service with Maven
        # Wichtig: Arbeitsverzeichnis auf den Data-Service setzen
        working-directory: ./ayurly-data-service
        # Der Befehl ./mvnw stellt sicher, dass der Maven Wrapper verwendet wird.
        # 'package' kompiliert, testet (standardmäßig) und packt die Anwendung.
        # -DskipTests kann hinzugefügt werden, um Tests im CI-Build zu überspringen, falls gewünscht,
        # aber es ist generell gut, sie hier laufen zu lassen.
        # Das Profil 'native' wird hier NICHT aktiviert, da wir das JVM-Dockerfile verwenden.
        run: ./mvnw package -DskipTests -Dquarkus.container-image.build=false # Verhindert, dass Quarkus selbst versucht, ein Image zu bauen

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ayurly-data-service
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image (Data Service)
        uses: docker/build-push-action@v6
        with:
          context: ./ayurly-data-service # Kontext ist das Verzeichnis des Data-Service
          file: ./ayurly-data-service/src/main/docker/Dockerfile.jvm # Pfad zum Quarkus JVM Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max